//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace WebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GOServicePortSoap11", Namespace="http://ws.services.getone.bcncons.com/")]
    public partial class GOServicePortService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processDocumentOperationCompleted;
        
        /// <remarks/>
        public GOServicePortService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["EndpointURL"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://172.16.221.20:9191/ws/GOService";
            }
        }
        
        /// <remarks/>
        public event processDocumentCompletedEventHandler processDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("processDocumentResponse", Namespace="http://ws.services.getone.bcncons.com/")]
        public processDocumentResponse processDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.services.getone.bcncons.com/")] processDocumentRequest processDocumentRequest) {
            object[] results = this.Invoke("processDocument", new object[] {
                        processDocumentRequest});
            return ((processDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprocessDocument(processDocumentRequest processDocumentRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processDocument", new object[] {
                        processDocumentRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public processDocumentResponse EndprocessDocument(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((processDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void processDocumentAsync(processDocumentRequest processDocumentRequest) {
            this.processDocumentAsync(processDocumentRequest, null);
        }
        
        /// <remarks/>
        public void processDocumentAsync(processDocumentRequest processDocumentRequest, object userState) {
            if ((this.processDocumentOperationCompleted == null)) {
                this.processDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDocumentOperationCompleted);
            }
            this.InvokeAsync("processDocument", new object[] {
                        processDocumentRequest}, this.processDocumentOperationCompleted, userState);
        }
        
        private void OnprocessDocumentOperationCompleted(object arg) {
            if ((this.processDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDocumentCompleted(this, new processDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.services.getone.bcncons.com/")]
    public partial class processDocumentRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string domain;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string doctype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string input;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.services.getone.bcncons.com/")]
    public partial class processDocumentResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void processDocumentCompletedEventHandler(object sender, processDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public processDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((processDocumentResponse)(this.results[0]));
            }
        }
    }
}
